### ISSUE TITLE
C03_P02 StackMin

### ISSUE THREAD

**Issue by rguan72** [careercup/CtCI-6th-Edition-Python#103]
The solution given for Chapter 3, Problem 2 is the solution for Chapter 3, Problem 1 (MultiStack). 
On line 4 in file ```32StackMin.py```, the solution begins with ```class MultiStack: ```

**Comment by jasonrhaas** [comment]
This is incorrect.  That file correctly solves the 3.2 problem.  The class name is the name but it has extra methods in there to solve for the `Min()`.

This issue should be closed.
