### ISSUE TITLE
How can I contribute solutions

### ISSUE THREAD

**Issue by deveshks** [careercup/CtCI-6th-Edition-Python#110]
I would love to be able to contribute missing solutions in Python to some of the chapters. 
Can I create a PR for such things?

**Comment by bandarji** [comment]
That's a fair question. Looking at the pull requests currently up for review, I doubt anyone's accepting updates. I mean, I have one from [summer 2018](https://github.com/careercup/CtCI-6th-Edition-Python/pull/67).

**Comment by deveshks** [comment]
Yes, seems like no-one has been maintaining this repo for quite some time. Not sure who can we ping to check with this. I am really interested in contributing to the repo since CTCI has helped me a lot in interviews in the past

**Comment by brycedrennan** [comment]
@deveshks @bandarji I'm on the job now. Quick get solutions in before I too fade away from maintenance! :smile:

**Comment by deveshks** [comment]
@brycedrennan Sorry I didn't get you. Are you saying that you will be maintaining the repo, and we can start contributing solutions which you will review and add to the repo?

**Comment by brycedrennan** [comment]
kind of yes.  but given that I'm a volunteer I may also have other priorities and limited time.
