### ISSUE TITLE
P02 - Need a correction for Prev refrerence

### ISSUE THREAD

**Issue by dheerajgm** [careercup/CtCI-6th-Edition-Python#113]
https://github.com/careercup/CtCI-6th-Edition-Python/blob/e6bc732588601d0a98e5b1bc44d83644b910978d/Chapter2/LinkedList.py#L67

**Comment by dheerajgm** [comment]
self.tail.next = Node(data, None, self.tail)

**Comment by brycedrennan** [comment]
Thanks this has now been fixed.
