### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by mbooali** [careercup/CtCI-6th-Edition-Python#125]
I liked to contribute to this repository by adding more answers, however, I am not sure if all of the code is in Python2 or Python3 and tested with which version. If you can clarify it or add it to README.md it would be great.

@mmermerkaya

**Comment by brycedrennan** [comment]
Just looking at the print statements, at least some of it is python 2.  I'd like to move everything to python 3 but not sure how much work is involved there.

**Comment by brycedrennan** [comment]
Okay well at least everything imports under python 3 now. I've updated the docs to say we prefer python 3.  Would welcome your contributions! @mbooali
