### ISSUE TITLE
Python - Chapter 1, Problem 2, URLify - input type string - suggest to either qualify question or adjust answer properly

### ISSUE THREAD

**Issue by drocpdp** [careercup/CtCI-6th-Edition-Python#130]
https://github.com/careercup/CtCI-6th-Edition-Python/blob/e6bc732588601d0a98e5b1bc44d83644b910978d/Chapter1/3_URLify/URLify.py#L24

In the book (p. 90) it specifies that we are to code for an input being a string. Yet this code seems to "cast" into a list before passing into URLify.py. 

I would think this converting string to list should be handled by the interviewee, since the question specifies input is of form string.

Can we either : 
1. in errata or future versions, clarify this in the question or
2. in the code, properly pass in the test cases as a type str and allow the user to convert in their algorithm?

Thanks in advance!!

**Comment by brycedrennan** [comment]
Good point - this has now been fixed in #124

**Comment by drocpdp** [comment]
> Good point - this has now been fixed in #124

Thanks!! Best wishes...
