### ISSUE TITLE
Chapter Two maybe test cases?

### ISSUE THREAD

**Issue by bravominski** [careercup/CtCI-6th-Edition-Python#16]
At this point, it generates random LinkedList and prints out.

Wouldn't it be better to come up with some test cases with solutions to check?

**Comment by bravominski** [comment]
Actually now that I went through chapter 2, realized we are not using any test cases here.
Any thoughts?

**Comment by brycedrennan** [comment]
I'm unclear on what you're referencing but we welcome pull requests with test cases
