### ISSUE TITLE
Get `ModuleNotFoundError: No module named 'chapter_04'` when I run `python3 chapter_04/p10_check_subtree.py`.

### ISSUE THREAD

**Issue by ryoyama0508** [careercup/CtCI-6th-Edition-Python#161]
When I try to run some`chapter_04` scripts like `python chapter_04/p10_check_subtree.py` or `python3 chapter_04/p10_check_subtree.py`, I got an error message like `ModuleNotFoundError: No module named 'chapter_04'`. This also happens when I try to run `python(python3) chapter_04/p09_bst_sequences.py`. And I double-checked that I run from the parent directory(workspace/CtCI-6th-Edition-Python). What is the problem?

For clarification, my IDE

- Python 3.8.2
- Visual Studio Code
- Using black 

This repository is used by a decent amount of people, so pretty sure this is not a mistake or anything and I misunderstood something. Please clarify that for me (or maybe other beginners).

**Comment by brycedrennan** [comment]
That is confusing. When you run a python script, the directory it's in is added to the pythonpath by default. In this case it's starting from `chapter_04` which means a reference to `chapter_04` at that path doesn't make sense.

You can tell python to run a module with this syntax, which will work:

```
python -m chapter_04.p10_check_subtree
```

**Comment by brycedrennan** [comment]
I agree it's somewhat confusing but I'm not sure how to make it easier. Let me know if you have an idea.

**Comment by ryoyama0508** [comment]
Thanks for your response. If referencing `chapter_04` at that path doesn't make sense, as you said, is the code itself the problem?
I mean code of `chapter_04/p10_check_subtree.py` starts like
```
from chapter_04.binary_tree import BinaryTree, Node
```

However, if I rewrite it like
```
from binary_tree import BinaryTree, Node
```
it works normally on my local computer when I run `python  chapter_04/p10_check_subtree.py`. The output is just `True`.

Should we change? Is it not what you are talking about?

**Comment by brycedrennan** [comment]
That would work for your specific case but would be more confusing overall for the project I think. The code isn't wrong, it's structured to all be in the same shared python path at the root of the project.   This is the normal way most projects would be set up.  That just wont work with the way you're trying to call it.

You can run it either by using the module notation I previously demonstrated or you could set the pythonpath yourself as well like this: 
```
PYTHONPATH=. python chapter_04/p10_check_subtree.py
```
and it would work as well.
