### ISSUE TITLE
Check_permutation by sort- compare sorted array

### ISSUE THREAD

**Issue by shaniklein** [careercup/CtCI-6th-Edition-Python#205]
Hi , why would you iterate over the sorted string ?
Could I just write the following code?

```
def check_permutation_by_sort(s1, s2):
    if len(s1)!=len(s2):
        return False
    return sorted(s1)==sorted(s2)
```

**Comment by brycedrennan** [comment]
Some solutions are written to demonstrate that you know how to do things "the hard way". Your suggestion is also fine and similar to one of the existing solutions: 
https://github.com/careercup/CtCI-6th-Edition-Python/blob/master/chapter_01/p02_check_permutation.py#L29-L33
