### ISSUE TITLE
Failed Test Cases.

### ISSUE THREAD

**Issue by Rohianon** [careercup/CtCI-6th-Edition-Python#251]
There is atleast one failed test case, what would the problem be?

**Comment by brycedrennan** [comment]
Not enough information provided to answer the question. The tests are all passing as can be seen here: https://github.com/careercup/CtCI-6th-Edition-Python/runs/8010023732?check_suite_focus=true

**Comment by Rohianon** [comment]
Here is my error output. 
I copied the whole code as it was. 

![image](https://user-images.githubusercontent.com/41194018/187158468-98c3363e-0a48-4f85-926f-09a121a91205.png)

**Comment by Rohianon** [comment]
This was the code I was using.

![image](https://user-images.githubusercontent.com/41194018/187159280-6b8ef42c-fbae-4a7a-8962-a36436070d65.png)

**Comment by brycedrennan** [comment]
That's not the code in this repo 🤷‍♂️   This is our current code: https://github.com/careercup/CtCI-6th-Edition-Python/blob/master/chapter_01/p04_palindrome_permutation.py

**Comment by Rohianon** [comment]
Okay, thank you Bryce for this info.

Warm Regards,
Rohi Anon Ogula

*Phone: +254795632662*
*Email: ***@***.*** ***@***.***>*

*Linked-in <https://www.linkedin.com/in/rohi-anon-38a026167/>.*
*Git-Hub Portfolio.* <https://github.com/Rohianon>
*Medium ***@***.***>.*
