### ISSUE TITLE
1.4 Question to the bit_vector

### ISSUE THREAD

**Issue by KantiCodes** [careercup/CtCI-6th-Edition-Python#262]
I was wondering that since we know that mask has only one bit, can we use 
```
r = r ^ mask
```
as opposed to
```
r &= ~mask
```

In this method:
```
def is_palindrome_bit_vector(phrase):
    """checks if a string is a permutation of a palindrome"""
    r = 0
    for c in clean_phrase(phrase):
        val = ord(c)
        mask = 1 << val
        if r & mask:
            r &= ~mask
        else:
            r |= mask
    return (r - 1) & r == 0
```

**Comment by brycedrennan** [comment]
Yes possibly. looks there is a test written for that problem so try it out and see if it works

https://github.com/careercup/CtCI-6th-Edition-Python/blob/6be09720f400e892d416747adde383545bc650d2/chapter_01/p04_palindrome_permutation.py#L97
