### ISSUE TITLE
PalindromePermutation.py bug

### ISSUE THREAD

**Issue by mulhod** [careercup/CtCI-6th-Edition-Python#4]
For palindromes that consist of an even number of characters, such as "No x in Nixon", the algorithm in `PalindromePermutation.py` does not correctly identify permutations as being permutations of a palindrome.

For example, the code below should evaluate to `True`, but it actually evaluates to `None` (and the same goes for any permutation of the input, all of which should evaluate to `True`):

```python
pal_perm("no x in nixon")
```

Am I misunderstanding the problem? In any case, it should evaluate to a boolean value. Currently, it will evaluate to `None`.

**Comment by mmermerkaya** [comment]
Hi, thanks for the bug report. You are correct. I made a quick fix, and added your example to the unit tests: 1181f4b

The solution we have right now seems to be O(N^2) though, which is not optimal. Thanks for bringing attention to this question, I'll change the implementation as soon as possible.
