### ISSUE TITLE
Chapter 2 Question 7 Test Case

### ISSUE THREAD

**Issue by erikyangs** [careercup/CtCI-6th-Edition-Python#58]
Noticed the question didn't have any tests. Hope this helps!
```
shared = LinkedList()
shared.add_multiple([1,2,3,4])

a = LinkedList([10,11,12,13,14,15])
b = LinkedList([20,21,22])

a.tail.next = shared.head
a.tail = shared.tail
b.tail.next = shared.head
b.tail = shared.tail

# should be 1
print(intersection(a,b))
```

**Comment by brycedrennan** [comment]
Thank you @erikyangs.  I've integrated your code here:

https://github.com/careercup/CtCI-6th-Edition-Python/blob/c4e659112dec568ab64126109139b2cfc3d502d5/Chapter02/7_Intersection.py
