### ISSUE TITLE
URLify.py

### ISSUE THREAD

**Issue by khanh** [careercup/CtCI-6th-Edition-Python#6]
I was under the impression that python strings are immutable as well. I tried compiling this code and it did indeed fail. In my own working solution I had to create a separate string and return that.

I took a more forward approach rather than the reverse route because of this:

```
def urlify(str, str_size):
    url_encoded

    for k,v in enumerate(str):
        if k < str_size:
            #size marks end of string
            if v == ' ':
                url_encoded += '%20'
            else:
                url_encoded += v
        else:
            break

    return url_encoded

```

**Comment by mmermerkaya** [comment]
Yours is also a valid solution and it works, but the question asks for an _in-place_ solution. That's why we used a character array (like the book suggests), and not a separate string.

**Comment by khanh** [comment]
I was actually going to post, i just saw that the unit test does use a character array. thanks.

**Comment by asaph** [comment]
This isn't the first time a non-in-place solution has been suggested as a replacement for this solution. See https://github.com/careercup/CtCI-6th-Edition/pull/31.
