### ISSUE TITLE
C01_P06 - Problem1.6 String compression edge case

### ISSUE THREAD

**Issue by 921kiyo** [careercup/CtCI-6th-Edition-Python#66]
I think the solution for 1.6 fails to return the correct answer when string = "aabb" (the answer a2b2 but returns aabb)

**Comment by fg91** [comment]
I think the solutions performs as intended. In the book it says "If the compressed string would not become smaller than the original string, [] return the original string".
a2b2 and aabb are both 4 characters so the correct return is aabb.

**Comment by BZAghalarov** [comment]
Hi guys,
I want to contribute this repo and added one solution but not merged repo?
What must I do to contribute this repo?
