### ISSUE TITLE
Examples and README.txt for problems

### ISSUE THREAD

**Issue by Twoody** [careercup/CtCI-6th-Edition-Python#71]
Incorporating a README.txt for relevant problems that require more skill (i.e. linear algebra, trig, Gauss/Zenos summation and calculus) and some numerical analysis know how would make this is a more complete series unto itself. This would incorporate general defenitions, examples, and explanations.

**Comment by brycedrennan** [comment]
We don't want this code repo to contain the content of the book.  Other than that we welcome pull requests improving the example solutions.
