### ISSUE TITLE
C01_P08 - Chapter 1: Zero Matrix

### ISSUE THREAD

**Issue by ShivamSomani** [careercup/CtCI-6th-Edition-Python#93]
the solution does not makes all the elements of row as 0.
for eg if array is = 
[[1,2,3,4,0],
[2,3,4,5,6,8,9,1,0],
[1,2,3,4,5,6,7,8,9,10,11,0]]   

then output coming is:
[[0, 0, 0, 0, 0], 
[2, 3, 4, 5, 0, 8, 9, 1, 0],
 [1, 2, 3, 4, 0, 6, 7, 8, 9, 10, 11, 0]]

although all the rows and columns in this solution should be 0, as mentioned in question.

**Comment by priyankasrs** [comment]
The inputs above are not m x n matrices!

**Comment by brycedrennan** [comment]
as @priyankasrs points out, those are not valid inputs for the question.  since they are not M x N matrices
