### ISSUE TITLE
C04_P02 Minimal Tree is wrong -> Creating a node with 2 parents

### ISSUE THREAD

**Issue by PabloRR100** [careercup/CtCI-6th-Edition-Python#99]
The solution provided at [problem_4.2][problem] is giving the following output for this array:

```
testArray = [1,2,3,4,8,12,13,99]

print(initiateArrayToBinary(testArray))
(((:L V:1 R:):L V:2 R:(:L V:3 R:)):L V:4 R:((:L V:8 R:):L V:12 R:(:L V:13 R:(:L V:99 R:))))
```

This will make node 8 to be the right child of root (4) and the left child of another root (12).

[problem]: https://github.com/careercup/CtCI-6th-Edition-Python/blob/master/Chapter4/42MinimalTree.py

**Comment by brycedrennan** [comment]
Looks like it was just a matter of a confusing way of displaying the tree.  I've updated the string representation and now the output looks like this:
```
4
L:2
  L:1
  R:3
R:12
  L:8
  R:13
    R:99
```
